#ifndef MAIN_H
#define MAIN_H
#include <iostream> 
#include <algorithm> 
#include "opencv2/core.hpp"
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/objdetect.hpp"
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/opencv.h>
#include "detector.h"
#include "recognizor.h"
#include <filesystem>
#include "performance.h"
#include "dlib/dir_nav/dir_nav_extensions.h"
// Multithreading
#include <mutex>
#include <atomic>
#include <thread>
#include <condition_variable>
#endif
